@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Apr 30 11:43:34 +0300 2022
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim seq_core_test_behav -key {Behavioral:sim_1:Functional:seq_core_test} -tclbatch seq_core_test.tcl -view C:/Users/bianca.palade/Desktop/assignment1/assign1.2 - Copy/testbench_behav.wcfg -log simulate.log"
call xsim  seq_core_test_behav -key {Behavioral:sim_1:Functional:seq_core_test} -tclbatch seq_core_test.tcl -view C:/Users/bianca.palade/Desktop/assignment1/assign1.2 - Copy/testbench_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
